echo 'this is my first pipeline'
stage 'scm'
echo 'this is get the source from github'
stage 'maven_build'
echo 'this is maven build'
stage 'test'
echo 'this is stage'
stage 'deploy'
echo 'this is deploy stage'
